In [2]:
import torch
import numpy as np
import pandas as pd

In [8]:
dataset = pd.read_csv("D:\Coding\Python Programming\Real estate.csv")

inputs = dataset[['X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores']]

targets = dataset[['Y house price of unit area']]

input_arr = np.array(inputs, dtype= 'float32')
target_arr = np.array(targets, dtype= 'float32')

inputs = torch.from_numpy(input_arr)

targets = torch.from_numpy(target_arr)

train_ds = torch.utils.data.TensorDataset(inputs, targets)
train_ds[0:3]

batch_size = 10

train_dl = torch.utils.data.DataLoader(train_ds, batch_size, shuffle = True)

model = torch.nn.Linear(3,1)

preds = model(inputs)

import  torch.nn.functional as F

loss = F.mse_loss


opt = torch.optim.SGD(model.parameters(), lr = 1e-8)

final_weights = torch.tensor([0])

final_bias = torch.tensor([0])

def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    for epoch in range(num_epochs):
        
        for xb,yb in train_dl:
            
            pred = model(xb)
            
            loss = loss_fn(pred, yb)
            
            loss.backward()
            
            opt.step()
            
            opt.zero_grad()
        if loss.item() <= 100:
            final_weights = model.weight
            final_bias = model.bias
            print(epoch)
            print(loss)
            print(model.weight)
            print(model.bias)
            # break
                

fit(1000, model, loss, opt, train_dl)



59
tensor(49.0935, grad_fn=<MseLossBackward>)
Parameter containing:
tensor([[-0.4791,  0.0144, -0.4194]], requires_grad=True)
Parameter containing:
tensor([0.1581], requires_grad=True)
889
tensor(70.2786, grad_fn=<MseLossBackward>)
Parameter containing:
tensor([[-0.1049,  0.0121, -0.2943]], requires_grad=True)
Parameter containing:
tensor([0.1792], requires_grad=True)


tensor([-3.5791], grad_fn=<AddBackward0>)
tensor([0.0633], grad_fn=<AddBackward0>)
tensor([4.5498], grad_fn=<AddBackward0>)
